### ISSUE TITLE
RecursionError: maximum recursion depth exceeded while getting the repr of an object

### ISSUE THREAD

**Issue by db0** [ermanh/trieregex#5]
I have an error when trying to use this library with a list of 10K celebrity names.
```
Traceback (most recent call last):
  File "/home/hhh/ratings-api/clean.py", line 74, in <module>
    logger.debug(trie.regex())
  File "/home/hhh/.local/lib/python3.9/site-packages/trieregex/memoizer.py", line 20, in __call__
    self.cache[stringed] = self.func(*args)
  File "/home/hhh/.local/lib/python3.9/site-packages/trieregex/trieregex.py", line 111, in regex
    return f'{escape(key)}{self.regex(trie[key], False)}'
  File "/home/hhh/.local/lib/python3.9/site-packages/trieregex/memoizer.py", line 18, in __call__
    stringed = str(args)
RecursionError: maximum recursion depth exceeded while getting the repr of an object
```

**Comment by PeopleCallHimThomas** [comment]
Same error for me when I try with a list of 30k

**Comment by zsw6666** [comment]
> I have an error when trying to use this library with a list of 10K celebrity names.
> 
> ```
> Traceback (most recent call last):
>   File "/home/hhh/ratings-api/clean.py", line 74, in <module>
>     logger.debug(trie.regex())
>   File "/home/hhh/.local/lib/python3.9/site-packages/trieregex/memoizer.py", line 20, in __call__
>     self.cache[stringed] = self.func(*args)
>   File "/home/hhh/.local/lib/python3.9/site-packages/trieregex/trieregex.py", line 111, in regex
>     return f'{escape(key)}{self.regex(trie[key], False)}'
>   File "/home/hhh/.local/lib/python3.9/site-packages/trieregex/memoizer.py", line 18, in __call__
>     stringed = str(args)
> RecursionError: maximum recursion depth exceeded while getting the repr of an object
> ```

Do you solve this error now? I met the same error...
